// GENERATED by server/scripts/api_types.sh from the server's pydantic models
// (server/holt_server/schema.py). Do not edit; run the script instead.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/badge/{owner}/{repo}.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Badge Svg */
        get: operations["badge_svg_badge__owner___repo__svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_v1_analyses__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Events */
        get: operations["analysis_events_v1_analyses__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find */
        post: operations["find_v1_find_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/find/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Find */
        get: operations["get_find_v1_find__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/find/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find Events */
        get: operations["find_events_v1_find__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record View
         * @description A signed-in user opened a report page. Kept only while GitHub is connected.
         */
        post: operations["record_view_v1_me_activity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Credits */
        get: operations["get_credits_v1_me_credits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/credits/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Claim */
        post: operations["post_claim_v1_me_credits_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Github */
        get: operations["get_github_v1_me_github_get"];
        put?: never;
        /** Connect Github */
        post: operations["connect_github_v1_me_github_post"];
        /** Disconnect Github */
        delete: operations["disconnect_github_v1_me_github_delete"];
        options?: never;
        head?: never;
        /** Github Settings */
        patch: operations["github_settings_v1_me_github_patch"];
        trace?: never;
    };
    "/v1/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_v1_me_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description The latest 7-day rules report per repository, newest first (sitemaps).
         */
        get: operations["list_reports_v1_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{owner}/{repo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_v1_reports__owner___repo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{owner}/{repo}/starter-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Starter Issues */
        get: operations["starter_issues_v1_repos__owner___repo__starter_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityIn */
        ActivityIn: {
            /** Repo */
            repo: string;
        };
        /** AnalysisDone */
        AnalysisDone: {
            report: components["schemas"]["Report"];
            /**
             * Status
             * @default done
             * @constant
             */
            status: "done";
        };
        /** AnalysisIn */
        AnalysisIn: {
            /**
             * Days
             * @default 7
             */
            days: number;
            /**
             * Mode
             * @default rules
             * @enum {string}
             */
            mode: "rules" | "ai";
            /**
             * Refresh
             * @default false
             */
            refresh: boolean;
            /** Repo */
            repo: string;
        };
        /** ConnectIn */
        ConnectIn: {
            /** Adult Confirmed */
            adult_confirmed: boolean;
            /** Github Id */
            github_id: number;
            /**
             * Stats Opt Out
             * @default false
             */
            stats_opt_out: boolean;
        };
        /** Cost */
        Cost: {
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
        };
        /**
         * Credits
         * @description Free AI reports: GET /v1/me/credits, and `credits` in GET /v1/me.
         */
        Credits: {
            /** Ai Available */
            ai_available: boolean;
            /** Balance */
            balance: number;
            /** Can Claim */
            can_claim: boolean;
            /** Claim Every Days */
            claim_every_days: number;
            /** Next Claim At */
            next_claim_at: string | null;
        };
        /** Error */
        Error: {
            /**
             * Code
             * @enum {string}
             */
            code: "unauthorized" | "not_found" | "invalid_repo" | "invalid_request" | "rate_limited" | "quota_exceeded" | "needs_key" | "claim_not_ready" | "ai_unavailable" | "upstream" | "internal" | "not_implemented";
            /** Message */
            message: string;
            /** Retry After */
            retry_after?: number | null;
        };
        /** ErrorBody */
        ErrorBody: {
            error: components["schemas"]["Error"];
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Quote */
            quote: string | null;
            /** Text */
            text: string;
            /** Url */
            url: string;
            /** Value */
            value: string | null;
        };
        /** FindDone */
        FindDone: {
            /** Results */
            results: components["schemas"]["FindResult"][];
            /**
             * Status
             * @default done
             * @constant
             */
            status: "done";
        };
        /** FindIn */
        FindIn: {
            /**
             * Days
             * @default 7
             */
            days: number;
            /**
             * Hacktoberfest
             * @default false
             */
            hacktoberfest: boolean;
            /** Languages */
            languages?: string[];
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /** Topics */
            topics?: string[];
        };
        /** FindJobStatus */
        FindJobStatus: {
            error: components["schemas"]["Error"] | null;
            /** Progress */
            progress: number;
            /** Results */
            results: components["schemas"]["FindResult"][] | null;
            /** Stage */
            stage: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error";
        };
        /** FindResult */
        FindResult: {
            /** Description */
            description: string | null;
            /** Headline */
            readonly headline: string;
            /** Issues */
            issues: components["schemas"]["StarterIssue"][];
            /** Language */
            language: string | null;
            /** Repo */
            repo: string;
            /** Stars */
            stars: number | null;
            stats: components["schemas"]["PartialStats"];
            /**
             * Tone
             * @enum {string}
             */
            readonly tone: "good" | "bad" | "warn";
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "viable" | "not_viable" | "insufficient_evidence";
        };
        /** GitHubAccount */
        GitHubAccount: {
            /** Adult Confirmed At */
            adult_confirmed_at: string;
            /** Connected At */
            connected_at: string;
            /** Id */
            id: number;
            /** Login */
            login: string;
            /** Stats Opt Out */
            stats_opt_out: boolean;
        };
        /** GitHubConnection */
        GitHubConnection: {
            account: components["schemas"]["GitHubAccount"] | null;
            /** Connected */
            connected: boolean;
        };
        /** GitHubSettingsIn */
        GitHubSettingsIn: {
            /** Stats Opt Out */
            stats_opt_out: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Database */
            database: boolean | null;
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
        };
        /** History */
        History: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Created At */
            created_at: string;
            /** Days */
            days: number;
            /** Headline */
            readonly headline: string | null;
            /** Job Id */
            job_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "ai";
            /** Repo */
            repo: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error";
            /** Tone */
            readonly tone: ("good" | "bad" | "warn") | null;
            /** Verdict */
            verdict: ("viable" | "not_viable" | "insufficient_evidence") | null;
        };
        /** JobStatus */
        JobStatus: {
            error: components["schemas"]["Error"] | null;
            /** Progress */
            progress: number;
            report: components["schemas"]["Report"] | null;
            /** Stage */
            stage: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error";
        };
        /** LandingPath */
        LandingPath: {
            /** Attempted */
            attempted: number;
            /** Merged */
            merged: number;
            /** Path */
            path: string;
        };
        /** Me */
        Me: {
            credits: components["schemas"]["Credits"];
            /** Plan */
            plan: string;
        };
        /** NeverLanded */
        NeverLanded: {
            /** Attempted */
            attempted: number;
            /** Path */
            path: string;
        };
        /**
         * Odds
         * @description A newcomer's chances, for a report whose verdict is `viable` only.
         */
        Odds: {
            /**
             * Level
             * @enum {string}
             */
            level: "good" | "fair" | "long";
            /** Text */
            text: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "good" | "bad" | "warn";
        };
        /**
         * PartialStats
         * @description The counts a find result carries: whichever the finder had. Counts it
         *     didn't have are left out, not null (a null reply time means "no replies").
         */
        PartialStats: {
            /** Bot Share */
            bot_share?: number | null;
            /** Distinct Outsiders */
            distinct_outsiders?: number | null;
            /** First Time Merged Authors */
            first_time_merged_authors?: number | null;
            /** Median First Response Hours */
            median_first_response_hours?: number | null;
            /** No Reply */
            no_reply?: number | null;
            /** Outsider Attempts */
            outsider_attempts?: number | null;
            /** Outsider Merged */
            outsider_merged?: number | null;
        };
        /** Queued */
        Queued: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /** Report */
        Report: {
            cost: components["schemas"]["Cost"] | null;
            /** Days */
            days: number;
            /** Decided By */
            decided_by: string[];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** Evidence Until */
            evidence_until: string | null;
            /** Generated At */
            generated_at: string;
            /** Headline */
            readonly headline: string;
            /** Landing */
            landing: components["schemas"]["LandingPath"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "ai";
            /** Never Landed */
            never_landed: components["schemas"]["NeverLanded"][];
            readonly odds: components["schemas"]["Odds"] | null;
            /** Repo */
            repo: string;
            /** Rule Codes */
            rule_codes: string[];
            stats: components["schemas"]["Stats"];
            /** Summary */
            summary: string | null;
            /**
             * Tone
             * @enum {string}
             */
            readonly tone: "good" | "bad" | "warn";
            /** Unknowns */
            unknowns: string[];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "viable" | "not_viable" | "insufficient_evidence";
            /** Verdict Line */
            readonly verdict_line: string;
        };
        /** ReportList */
        ReportList: {
            /** Reports */
            reports: components["schemas"]["ReportListItem"][];
        };
        /** ReportListItem */
        ReportListItem: {
            /** Generated At */
            generated_at: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "ai";
            /** Repo */
            repo: string;
            /** Verdict */
            verdict: ("viable" | "not_viable" | "insufficient_evidence") | null;
        };
        /** StarterIssue */
        StarterIssue: {
            /**
             * Comments
             * @default 0
             */
            comments: number;
            /** Created At */
            created_at: string | null;
            /** Labels */
            labels: string[];
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Why */
            why: string[];
        };
        /** StarterIssues */
        StarterIssues: {
            /** Issues */
            issues: components["schemas"]["StarterIssue"][];
            /** Repo */
            repo: string;
        };
        /** Stats */
        Stats: {
            /** Bot Share */
            bot_share: number;
            /** Distinct Outsiders */
            distinct_outsiders: number;
            /** First Time Merged Authors */
            first_time_merged_authors: number;
            /** Median First Response Hours */
            median_first_response_hours: number | null;
            /** No Reply */
            no_reply: number;
            /** Outsider Attempts */
            outsider_attempts: number;
            /** Outsider Merged */
            outsider_merged: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type ActivityIn = components['schemas']['ActivityIn'];
export type AnalysisDone = components['schemas']['AnalysisDone'];
export type AnalysisIn = components['schemas']['AnalysisIn'];
export type ConnectIn = components['schemas']['ConnectIn'];
export type Cost = components['schemas']['Cost'];
export type Credits = components['schemas']['Credits'];
export type Error = components['schemas']['Error'];
export type ErrorBody = components['schemas']['ErrorBody'];
export type EvidenceItem = components['schemas']['EvidenceItem'];
export type FindDone = components['schemas']['FindDone'];
export type FindIn = components['schemas']['FindIn'];
export type FindJobStatus = components['schemas']['FindJobStatus'];
export type FindResult = components['schemas']['FindResult'];
export type GitHubAccount = components['schemas']['GitHubAccount'];
export type GitHubConnection = components['schemas']['GitHubConnection'];
export type GitHubSettingsIn = components['schemas']['GitHubSettingsIn'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type Health = components['schemas']['Health'];
export type History = components['schemas']['History'];
export type HistoryItem = components['schemas']['HistoryItem'];
export type JobStatus = components['schemas']['JobStatus'];
export type LandingPath = components['schemas']['LandingPath'];
export type Me = components['schemas']['Me'];
export type NeverLanded = components['schemas']['NeverLanded'];
export type Odds = components['schemas']['Odds'];
export type PartialStats = components['schemas']['PartialStats'];
export type Queued = components['schemas']['Queued'];
export type Report = components['schemas']['Report'];
export type ReportList = components['schemas']['ReportList'];
export type ReportListItem = components['schemas']['ReportListItem'];
export type StarterIssue = components['schemas']['StarterIssue'];
export type StarterIssues = components['schemas']['StarterIssues'];
export type Stats = components['schemas']['Stats'];
export type ValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    badge_svg_badge__owner___repo__svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    create_analysis_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDone"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queued"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_analysis_v1_analyses__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    analysis_events_v1_analyses__job_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    find_v1_find_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindDone"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queued"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_find_v1_find__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindJobStatus"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    find_events_v1_find__job_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    record_view_v1_me_activity_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_credits_v1_me_credits_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credits"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    post_claim_v1_me_credits_claim_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credits"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_github_v1_me_github_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubConnection"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    connect_github_v1_me_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubConnection"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    disconnect_github_v1_me_github_delete: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubConnection"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    github_settings_v1_me_github_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubConnection"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    history_v1_me_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_reports_v1_reports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportList"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_report_v1_reports__owner___repo__get: {
        parameters: {
            query?: {
                mode?: "rules" | "ai";
                days?: number;
            };
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                owner: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    starter_issues_v1_repos__owner___repo__starter_issues_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path: {
                owner: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StarterIssues"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
