// GENERATED by server/scripts/api_types.sh from the server's pydantic models
// (server/holt_server/schema.py). Do not edit; run the script instead.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/badge/{owner}/{repo}.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Badge Svg */
        get: operations["badge_svg_badge__owner___repo__svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pricing
         * @description The features, plans and packs this server loaded (prices in minor units).
         */
        get: operations["get_pricing_v1_admin_pricing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Newest users first, with balances. `plan` filters on the stored plan.
         */
        get: operations["list_users_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_v1_admin_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_v1_analyses__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Events */
        get: operations["analysis_events_v1_analyses__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Feedback */
        post: operations["post_feedback_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find */
        post: operations["find_v1_find_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/find/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Find */
        get: operations["get_find_v1_find__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/find/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find Events */
        get: operations["find_events_v1_find__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record View
         * @description A signed-in user opened a report page. Kept only while GitHub is connected.
         */
        post: operations["record_view_v1_me_activity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contributions
         * @description The stored list. The first time (or after a rename) it reads GitHub.
         */
        get: operations["get_contributions_v1_me_contributions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/contributions/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Contributions
         * @description Read GitHub again, unless the last read is under 15 minutes old: then
         *     the stored list comes back unchanged, with `next_refresh_at`.
         */
        post: operations["refresh_contributions_v1_me_contributions_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Credits */
        get: operations["get_credits_v1_me_credits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/credits/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Claim */
        post: operations["post_claim_v1_me_credits_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me Entitlements
         * @description Each paid feature: can this user use it now, and what would it cost.
         */
        get: operations["me_entitlements_v1_me_entitlements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Github */
        get: operations["get_github_v1_me_github_get"];
        put?: never;
        /** Connect Github */
        post: operations["connect_github_v1_me_github_post"];
        /** Disconnect Github */
        delete: operations["disconnect_github_v1_me_github_delete"];
        options?: never;
        head?: never;
        /** Github Settings */
        patch: operations["github_settings_v1_me_github_patch"];
        trace?: never;
    };
    "/v1/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_v1_me_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_v1_me_profile_get"];
        /** Put Profile */
        put: operations["put_profile_v1_me_profile_put"];
        post?: never;
        /** Delete Profile */
        delete: operations["delete_profile_v1_me_profile_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metric
         * @description Internal (the internal key, like every /v1 route): no user needed.
         */
        get: operations["get_metric_v1_metrics_contributions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description The latest 7-day rules report per repository, newest first (sitemaps).
         */
        get: operations["list_reports_v1_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{owner}/{repo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_v1_reports__owner___repo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{owner}/{repo}/starter-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Starter Issues */
        get: operations["starter_issues_v1_repos__owner___repo__starter_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Access
         * @description Whether this user can use one feature now, and what it would cost.
         */
        Access: {
            /** Allowed */
            allowed: boolean;
            /** Code */
            code: string | null;
            /** Cost */
            cost: number;
            /** Feature */
            feature: string;
            /** Left This Month */
            left_this_month: number | null;
            /** Message */
            message: string | null;
            /** Name */
            name: string;
            /** Via */
            via: ("plan" | "credits") | null;
        };
        /** ActivityIn */
        ActivityIn: {
            /** Repo */
            repo: string;
        };
        /** AdminCreditEvent */
        AdminCreditEvent: {
            /** Actor */
            actor: string | null;
            /** Amount */
            amount: number;
            /** Created At */
            created_at: string;
            /** Feature */
            feature: string | null;
            /** Id */
            id: number;
            /** Job Id */
            job_id: string | null;
            /** Kind */
            kind: string;
            /** Lot Id */
            lot_id: number | null;
            /** Reason */
            reason: string | null;
            /** Source */
            source: string;
        };
        /** AdminLot */
        AdminLot: {
            /** Created At */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /** Granted */
            granted: number;
            /** Id */
            id: number;
            /** Origin */
            origin: string;
            /** Pack Id */
            pack_id: string | null;
            /** Reference */
            reference: string | null;
            /** Remaining */
            remaining: number;
        };
        /** AdminPlanEvent */
        AdminPlanEvent: {
            /** Actor */
            actor: string | null;
            /** Created At */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /** Id */
            id: number;
            /** Plan */
            plan: string;
            /** Reason */
            reason: string | null;
            /** Reference */
            reference: string | null;
        };
        /** AdminPlanUsage */
        AdminPlanUsage: {
            /** Feature */
            feature: string;
            /** Period */
            period: string;
            /** Used */
            used: number;
        };
        /**
         * AdminUser
         * @description GET /v1/admin/users/{user_id}: everything about one user's money.
         */
        AdminUser: {
            /** Access */
            access: components["schemas"]["Access"][];
            /** Created At */
            created_at: string;
            /** Effective Plan */
            effective_plan: string;
            /** Free */
            free: number;
            /** Id */
            id: string;
            /** Ledger */
            ledger: components["schemas"]["AdminCreditEvent"][];
            /** Lots */
            lots: components["schemas"]["AdminLot"][];
            /** Plan */
            plan: string;
            /** Plan Expires At */
            plan_expires_at: string | null;
            /** Plan History */
            plan_history: components["schemas"]["AdminPlanEvent"][];
            /** Plan Usage */
            plan_usage: components["schemas"]["AdminPlanUsage"][];
            /** Purchased */
            purchased: number;
        };
        /** AdminUserSummary */
        AdminUserSummary: {
            /** Created At */
            created_at: string;
            /** Effective Plan */
            effective_plan: string;
            /** Free */
            free: number;
            /** Id */
            id: string;
            /** Plan */
            plan: string;
            /** Plan Expires At */
            plan_expires_at: string | null;
            /** Purchased */
            purchased: number;
        };
        /** AdminUsers */
        AdminUsers: {
            /** Users */
            users: components["schemas"]["AdminUserSummary"][];
        };
        /** AnalysisDone */
        AnalysisDone: {
            report: components["schemas"]["Report"];
            /**
             * Status
             * @default done
             * @constant
             */
            status: "done";
        };
        /** AnalysisIn */
        AnalysisIn: {
            /**
             * Days
             * @default 7
             */
            days: number;
            /**
             * Mode
             * @default rules
             * @enum {string}
             */
            mode: "rules" | "ai";
            /**
             * Refresh
             * @default false
             */
            refresh: boolean;
            /** Repo */
            repo: string;
        };
        /**
         * Ask
         * @description Something the project asks of a contributor before a pull request, and
         *     where Holt read it (a CLA bot's comment, or CONTRIBUTING).
         */
        Ask: {
            /**
             * Code
             * @enum {string}
             */
            code: "cla" | "dco" | "issue_first";
            /** Url */
            url: string;
        };
        /** Catalogue */
        Catalogue: {
            /**
             * About
             * @default
             */
            _about: string;
            /** Features */
            features: {
                [key: string]: components["schemas"]["Feature"];
            };
            /**
             * Packs
             * @default {}
             */
            packs: {
                [key: string]: components["schemas"]["Pack"];
            };
            /** Plans */
            plans: {
                [key: string]: components["schemas"]["Plan"];
            };
            /**
             * Tbd
             * @default true
             */
            tbd: boolean;
        };
        /** ConnectIn */
        ConnectIn: {
            /** Adult Confirmed */
            adult_confirmed: boolean;
            /** Github Id */
            github_id: number;
            /**
             * Stats Opt Out
             * @default false
             */
            stats_opt_out: boolean;
        };
        /**
         * ContributionMetric
         * @description The product metric: pull requests opened after checking a repo on Holt.
         *     Counts only, no people.
         */
        ContributionMetric: {
            /** Connected Users */
            connected_users: number;
            /** Prs After Holt */
            prs_after_holt: number;
            /** Prs After Holt Merged */
            prs_after_holt_merged: number;
            /** Since */
            since: string;
            /** Users With Pr After Holt */
            users_with_pr_after_holt: number;
            /** Users With Pull Requests */
            users_with_pull_requests: number;
            /** Window Days */
            window_days: number;
        };
        /** ContributionPullRequest */
        ContributionPullRequest: {
            /** Closed At */
            closed_at: string | null;
            /** Created At */
            created_at: string;
            /** Draft */
            draft: boolean;
            /** Found Via Holt */
            found_via_holt: boolean;
            /** Merged At */
            merged_at: string | null;
            /** Number */
            number: number;
            /** Repo */
            repo: string;
            /**
             * State
             * @enum {string}
             */
            state: "open" | "merged" | "closed";
            /** Title */
            title: string;
            /** Url */
            url: string;
            verdict: components["schemas"]["RepoVerdict"] | null;
        };
        /** ContributionSummary */
        ContributionSummary: {
            /** Closed */
            closed: number;
            /** Found Via Holt */
            found_via_holt: number;
            /** Landed Share */
            landed_share: number | null;
            /** Merged */
            merged: number;
            /** Opened */
            opened: number;
            /** Waiting */
            waiting: number;
        };
        /** Contributions */
        Contributions: {
            /** Fetched At */
            fetched_at: string;
            /** Login */
            login: string;
            /** Next Refresh At */
            next_refresh_at: string | null;
            /** Pull Requests */
            pull_requests: components["schemas"]["ContributionPullRequest"][];
            summary: components["schemas"]["ContributionSummary"];
            /** Truncated */
            truncated: boolean;
            /** Window Days */
            window_days: number;
        };
        /** Cost */
        Cost: {
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /** Seconds */
            seconds: number | null;
            /** Usd */
            usd: number | null;
        };
        /**
         * Counted
         * @description One entry of "How this was counted".
         */
        Counted: {
            /** Text */
            text: string;
            /** Topic */
            topic: string;
        };
        /**
         * Credits
         * @description Credits: GET /v1/me/credits, and `credits` in GET /v1/me.
         */
        Credits: {
            /** Ai Available */
            ai_available: boolean;
            /** Balance */
            balance: number;
            /** Can Claim */
            can_claim: boolean;
            /** Claim Every Days */
            claim_every_days: number;
            /** Free */
            free: number;
            /** Next Claim At */
            next_claim_at: string | null;
            /** Purchased */
            purchased: number;
        };
        /**
         * Entitlements
         * @description GET /v1/me/entitlements.
         */
        Entitlements: {
            /** Features */
            features: components["schemas"]["Access"][];
            /** Plan */
            plan: string;
            /** Plan Expires At */
            plan_expires_at: string | null;
        };
        /** Error */
        Error: {
            /**
             * Code
             * @enum {string}
             */
            code: "unauthorized" | "not_found" | "invalid_repo" | "invalid_request" | "rate_limited" | "quota_exceeded" | "needs_key" | "claim_not_ready" | "ai_unavailable" | "upstream" | "internal" | "not_implemented";
            /** Message */
            message: string;
            /** Retry After */
            retry_after?: number | null;
        };
        /** ErrorBody */
        ErrorBody: {
            error: components["schemas"]["Error"];
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Quote */
            quote: string | null;
            /** Text */
            text: string;
            /** Url */
            url: string;
            /** Value */
            value: string | null;
        };
        /** Feature */
        Feature: {
            /** Credits */
            credits?: number | null;
            /**
             * Free Credits
             * @default false
             */
            free_credits: boolean;
            /** Name */
            name: string;
        };
        /** FeedbackIn */
        FeedbackIn: {
            /**
             * Days
             * @default 7
             */
            days: number;
            /** Generated At */
            generated_at: string;
            /**
             * Mode
             * @default rules
             * @enum {string}
             */
            mode: "rules" | "ai";
            /** Reason */
            reason?: string | null;
            /** Repo */
            repo: string;
            /**
             * Vote
             * @enum {string}
             */
            vote: "up" | "down";
        };
        /**
         * FeedbackOut
         * @description The answer as saved, with the verdict of the report it is about.
         */
        FeedbackOut: {
            /** Generated At */
            generated_at: string;
            /** Reason */
            reason: string | null;
            /** Repo */
            repo: string;
            /** Verdict */
            verdict: string;
            /**
             * Vote
             * @enum {string}
             */
            vote: "up" | "down";
        };
        /** FindDone */
        FindDone: {
            /** Results */
            results: components["schemas"]["FindResult"][];
            /**
             * Status
             * @default done
             * @constant
             */
            status: "done";
        };
        /** FindIn */
        FindIn: {
            /**
             * Days
             * @default 7
             */
            days: number;
            /**
             * Hacktoberfest
             * @default false
             */
            hacktoberfest: boolean;
            /** Languages */
            languages?: string[];
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /** Topics */
            topics?: string[];
        };
        /** FindJobStatus */
        FindJobStatus: {
            error: components["schemas"]["Error"] | null;
            /** Progress */
            progress: number;
            /** Results */
            results: components["schemas"]["FindResult"][] | null;
            /** Stage */
            stage: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error";
        };
        /** FindResult */
        FindResult: {
            /** Description */
            description: string | null;
            /** Headline */
            readonly headline: string;
            /** Issues */
            issues: components["schemas"]["StarterIssue"][];
            /** Language */
            language: string | null;
            /** Repo */
            repo: string;
            /** Stars */
            stars: number | null;
            stats: components["schemas"]["PartialStats"];
            /**
             * Tone
             * @enum {string}
             */
            readonly tone: "good" | "bad" | "warn";
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "viable" | "not_viable" | "insufficient_evidence";
        };
        /** GitHubAccount */
        GitHubAccount: {
            /** Adult Confirmed At */
            adult_confirmed_at: string;
            /** Connected At */
            connected_at: string;
            /** Id */
            id: number;
            /** Login */
            login: string;
            /** Stats Opt Out */
            stats_opt_out: boolean;
        };
        /** GitHubConnection */
        GitHubConnection: {
            account: components["schemas"]["GitHubAccount"] | null;
            /** Connected */
            connected: boolean;
        };
        /** GitHubSettingsIn */
        GitHubSettingsIn: {
            /** Stats Opt Out */
            stats_opt_out: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Database */
            database: boolean | null;
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
        };
        /** History */
        History: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Created At */
            created_at: string;
            /** Days */
            days: number;
            /** Headline */
            readonly headline: string | null;
            /** Job Id */
            job_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "ai";
            /** Repo */
            repo: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error";
            /** Tone */
            readonly tone: ("good" | "bad" | "warn") | null;
            /** Verdict */
            verdict: ("viable" | "not_viable" | "insufficient_evidence") | null;
        };
        /**
         * HoltUsers
         * @description Pull requests that connected Holt users sent to this repository in the
         *     last `window_days`: counts only. Present only when at least 5 people who
         *     didn't opt out of statistics make up the numbers (repo_stats.py).
         */
        HoltUsers: {
            /** Closed */
            closed: number;
            /** Computed At */
            computed_at: string;
            /** Merged */
            merged: number;
            /** People */
            people: number;
            /** Pull Requests */
            pull_requests: number;
            /** Waiting */
            waiting: number;
            /** Window Days */
            window_days: number;
        };
        /** JobStatus */
        JobStatus: {
            error: components["schemas"]["Error"] | null;
            /** Progress */
            progress: number;
            report: components["schemas"]["Report"] | null;
            /** Stage */
            stage: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error";
        };
        /** LandingPath */
        LandingPath: {
            /** Attempted */
            attempted: number;
            /** Merged */
            merged: number;
            /** Path */
            path: string;
        };
        /** Me */
        Me: {
            credits: components["schemas"]["Credits"];
            /** Plan */
            plan: string;
            /** Plan Expires At */
            plan_expires_at: string | null;
        };
        /** NeverLanded */
        NeverLanded: {
            /** Attempted */
            attempted: number;
            /** Path */
            path: string;
        };
        /**
         * Odds
         * @description A newcomer's chances, for a report whose verdict is `viable` only.
         */
        Odds: {
            /**
             * Level
             * @enum {string}
             */
            level: "good" | "fair" | "long";
            /** Text */
            text: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "good" | "bad" | "warn";
        };
        /** Pack */
        Pack: {
            /** Credits */
            credits: number;
            /** Expires Days */
            expires_days?: number | null;
            /** Name */
            name: string;
            /**
             * On Sale
             * @default false
             */
            on_sale: boolean;
            /** @default {} */
            price: components["schemas"]["Price"];
        };
        /**
         * PartialStats
         * @description The counts a find result carries: whichever the finder had. Counts it
         *     didn't have are left out, not null (a null reply time means "no replies").
         */
        PartialStats: {
            /** Bot Share */
            bot_share?: number | null;
            /** Distinct Outsiders */
            distinct_outsiders?: number | null;
            /** First Time Merged Authors */
            first_time_merged_authors?: number | null;
            /** Median First Response Hours */
            median_first_response_hours?: number | null;
            /** No Reply */
            no_reply?: number | null;
            /** Outsider Attempts */
            outsider_attempts?: number | null;
            /** Outsider Merged */
            outsider_merged?: number | null;
        };
        /** Plan */
        Plan: {
            /**
             * Features
             * @default {}
             */
            features: {
                [key: string]: components["schemas"]["PlanFeature"];
            };
            /** Name */
            name: string;
            /**
             * On Sale
             * @default false
             */
            on_sale: boolean;
            /** Period Days */
            period_days?: number | null;
            /** @default {} */
            price: components["schemas"]["Price"];
        };
        /** PlanFeature */
        PlanFeature: {
            /** Per Month */
            per_month?: number | null;
            /**
             * Unlimited
             * @default false
             */
            unlimited: boolean;
        };
        /** Price */
        Price: {
            /** Inr Paise */
            inr_paise?: number | null;
            /** Usd Cents */
            usd_cents?: number | null;
        };
        /** ProfileIn */
        ProfileIn: {
            /**
             * Adult Confirmed
             * @default false
             */
            adult_confirmed: boolean;
            /** Contributions */
            contributions?: ("code" | "docs" | "tests" | "design" | "translations")[];
            /**
             * Days
             * @default 7
             */
            days: number;
            /** Languages */
            languages?: string[];
            /**
             * Level
             * @default newcomer
             * @enum {string}
             */
            level: "newcomer" | "experienced";
            /** Topics */
            topics?: string[];
        };
        /** ProfileOut */
        ProfileOut: {
            /** Adult Confirmed */
            adult_confirmed: boolean;
            profile: components["schemas"]["ProfilePrefs"] | null;
        };
        /** ProfilePrefs */
        ProfilePrefs: {
            /** Contributions */
            contributions: ("code" | "docs" | "tests" | "design" | "translations")[];
            /**
             * Days
             * @default 7
             */
            days: number;
            /** Languages */
            languages: string[];
            /**
             * Level
             * @default newcomer
             * @enum {string}
             */
            level: "newcomer" | "experienced";
            /** Topics */
            topics: string[];
            /** Updated At */
            updated_at: string | null;
        };
        /** Queued */
        Queued: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /**
         * RepoVerdict
         * @description Holt's latest rules verdict for a repository, from the report cache.
         */
        RepoVerdict: {
            /** Checked At */
            checked_at: string;
            /** Headline */
            readonly headline: string;
            /**
             * Tone
             * @enum {string}
             */
            readonly tone: "good" | "bad" | "warn";
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "viable" | "not_viable" | "insufficient_evidence";
        };
        /** Report */
        Report: {
            /** Asks */
            asks: components["schemas"]["Ask"][];
            /** Bottom Line */
            bottom_line: string | null;
            cost: components["schemas"]["Cost"] | null;
            /** Counted */
            readonly counted: components["schemas"]["Counted"][];
            /** Days */
            days: number;
            /** Decided By */
            decided_by: string[];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** Evidence Until */
            evidence_until: string | null;
            /** First Timer Line */
            readonly first_timer_line: string | null;
            /** Generated At */
            generated_at: string;
            /** Headline */
            readonly headline: string;
            holt_users: components["schemas"]["HoltUsers"] | null;
            /** Landing */
            landing: components["schemas"]["LandingPath"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "ai";
            /** Never Landed */
            never_landed: components["schemas"]["NeverLanded"][];
            /** Next Step */
            readonly next_step: string;
            /** Numbers Line */
            readonly numbers_line: string;
            readonly odds: components["schemas"]["Odds"] | null;
            /** Repo */
            repo: string;
            /** Rule Codes */
            rule_codes: string[];
            sample: components["schemas"]["Sample"] | null;
            /** Stat Line */
            readonly stat_line: string | null;
            stats: components["schemas"]["Stats"];
            /** Summary */
            summary: string | null;
            /**
             * Tone
             * @enum {string}
             */
            readonly tone: "good" | "bad" | "warn";
            /** Unknowns */
            unknowns: string[];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "viable" | "not_viable" | "insufficient_evidence";
            /** Verdict Line */
            readonly verdict_line: string;
        };
        /** ReportList */
        ReportList: {
            /** Reports */
            reports: components["schemas"]["ReportListItem"][];
        };
        /** ReportListItem */
        ReportListItem: {
            /** Generated At */
            generated_at: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "rules" | "ai";
            /** Repo */
            repo: string;
            /** Verdict */
            verdict: ("viable" | "not_viable" | "insufficient_evidence") | null;
        };
        /**
         * Sample
         * @description What the counts were read from: the newest pull requests, and who was
         *     left out of them before counting.
         */
        Sample: {
            /** Bot Pull Requests */
            bot_pull_requests: number;
            /** First Opened */
            first_opened: string | null;
            /** Last Opened */
            last_opened: string | null;
            /** Pull Requests */
            pull_requests: number;
            /** Team People */
            team_people: number;
            /** Team Pull Requests */
            team_pull_requests: number;
        };
        /** StarterIssue */
        StarterIssue: {
            /** Areas */
            readonly areas: ("code" | "docs" | "tests" | "design" | "translations")[];
            /** Beginner */
            readonly beginner: boolean;
            /**
             * Comments
             * @default 0
             */
            comments: number;
            /** Created At */
            created_at: string | null;
            /** Labels */
            labels: string[];
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Why */
            why: string[];
        };
        /** StarterIssues */
        StarterIssues: {
            /** Issues */
            issues: components["schemas"]["StarterIssue"][];
            /** Repo */
            repo: string;
        };
        /** Stats */
        Stats: {
            /** Bot Share */
            bot_share: number;
            /** Distinct Outsiders */
            distinct_outsiders: number;
            /** First Time Merged Authors */
            first_time_merged_authors: number;
            /** Median First Response Hours */
            median_first_response_hours: number | null;
            /** No Reply */
            no_reply: number;
            /** Outsider Attempts */
            outsider_attempts: number;
            /** Outsider Merged */
            outsider_merged: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Access = components['schemas']['Access'];
export type ActivityIn = components['schemas']['ActivityIn'];
export type AdminCreditEvent = components['schemas']['AdminCreditEvent'];
export type AdminLot = components['schemas']['AdminLot'];
export type AdminPlanEvent = components['schemas']['AdminPlanEvent'];
export type AdminPlanUsage = components['schemas']['AdminPlanUsage'];
export type AdminUser = components['schemas']['AdminUser'];
export type AdminUserSummary = components['schemas']['AdminUserSummary'];
export type AdminUsers = components['schemas']['AdminUsers'];
export type AnalysisDone = components['schemas']['AnalysisDone'];
export type AnalysisIn = components['schemas']['AnalysisIn'];
export type Ask = components['schemas']['Ask'];
export type Catalogue = components['schemas']['Catalogue'];
export type ConnectIn = components['schemas']['ConnectIn'];
export type ContributionMetric = components['schemas']['ContributionMetric'];
export type ContributionPullRequest = components['schemas']['ContributionPullRequest'];
export type ContributionSummary = components['schemas']['ContributionSummary'];
export type Contributions = components['schemas']['Contributions'];
export type Cost = components['schemas']['Cost'];
export type Counted = components['schemas']['Counted'];
export type Credits = components['schemas']['Credits'];
export type Entitlements = components['schemas']['Entitlements'];
export type Error = components['schemas']['Error'];
export type ErrorBody = components['schemas']['ErrorBody'];
export type EvidenceItem = components['schemas']['EvidenceItem'];
export type Feature = components['schemas']['Feature'];
export type FeedbackIn = components['schemas']['FeedbackIn'];
export type FeedbackOut = components['schemas']['FeedbackOut'];
export type FindDone = components['schemas']['FindDone'];
export type FindIn = components['schemas']['FindIn'];
export type FindJobStatus = components['schemas']['FindJobStatus'];
export type FindResult = components['schemas']['FindResult'];
export type GitHubAccount = components['schemas']['GitHubAccount'];
export type GitHubConnection = components['schemas']['GitHubConnection'];
export type GitHubSettingsIn = components['schemas']['GitHubSettingsIn'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type Health = components['schemas']['Health'];
export type History = components['schemas']['History'];
export type HistoryItem = components['schemas']['HistoryItem'];
export type HoltUsers = components['schemas']['HoltUsers'];
export type JobStatus = components['schemas']['JobStatus'];
export type LandingPath = components['schemas']['LandingPath'];
export type Me = components['schemas']['Me'];
export type NeverLanded = components['schemas']['NeverLanded'];
export type Odds = components['schemas']['Odds'];
export type Pack = components['schemas']['Pack'];
export type PartialStats = components['schemas']['PartialStats'];
export type Plan = components['schemas']['Plan'];
export type PlanFeature = components['schemas']['PlanFeature'];
export type Price = components['schemas']['Price'];
export type ProfileIn = components['schemas']['ProfileIn'];
export type ProfileOut = components['schemas']['ProfileOut'];
export type ProfilePrefs = components['schemas']['ProfilePrefs'];
export type Queued = components['schemas']['Queued'];
export type RepoVerdict = components['schemas']['RepoVerdict'];
export type Report = components['schemas']['Report'];
export type ReportList = components['schemas']['ReportList'];
export type ReportListItem = components['schemas']['ReportListItem'];
export type Sample = components['schemas']['Sample'];
export type StarterIssue = components['schemas']['StarterIssue'];
export type StarterIssues = components['schemas']['StarterIssues'];
export type Stats = components['schemas']['Stats'];
export type ValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    badge_svg_badge__owner___repo__svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_pricing_v1_admin_pricing_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogue"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_users_v1_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                plan?: string | null;
            };
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsers"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_user_v1_admin_users__user_id__get: {
        parameters: {
            query?: {
                ledger_limit?: number;
            };
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_analysis_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDone"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queued"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_analysis_v1_analyses__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    analysis_events_v1_analyses__job_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    post_feedback_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_v1_find_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindDone"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queued"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_find_v1_find__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindJobStatus"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    find_events_v1_find__job_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    record_view_v1_me_activity_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_contributions_v1_me_contributions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contributions"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    refresh_contributions_v1_me_contributions_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contributions"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_credits_v1_me_credits_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credits"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    post_claim_v1_me_credits_claim_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credits"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    me_entitlements_v1_me_entitlements_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entitlements"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_github_v1_me_github_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubConnection"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    connect_github_v1_me_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubConnection"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    disconnect_github_v1_me_github_delete: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubConnection"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    github_settings_v1_me_github_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubConnection"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    history_v1_me_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_profile_v1_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    put_profile_v1_me_profile_put: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_profile_v1_me_profile_delete: {
        parameters: {
            query?: never;
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_metric_v1_metrics_contributions_get: {
        parameters: {
            query?: {
                since?: string | null;
            };
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionMetric"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_reports_v1_reports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportList"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_report_v1_reports__owner___repo__get: {
        parameters: {
            query?: {
                mode?: "rules" | "ai";
                days?: number;
            };
            header?: {
                "x-holt-internal-key"?: string | null;
            };
            path: {
                owner: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    starter_issues_v1_repos__owner___repo__starter_issues_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-holt-user"?: string | null;
                "x-holt-client-ip"?: string | null;
                "x-holt-internal-key"?: string | null;
            };
            path: {
                owner: string;
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StarterIssues"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
