// A recorded report: the landing's report when the live one is slow. The
// example merge plan (EXAMPLE_PATH) is lib/merge-plan.ts. The JSON is generated by `uv run python scripts/build_example_report.py` (replay
// only, no model spend); regenerate it when the pipeline changes.
import type { Report } from "./types.ts";
import data from "./example-ai-report.json" with { type: "json" };

/** The example merge plan. /example-ai-report lands here (lib/shell.ts, RETIRED). */
export const EXAMPLE_PATH = "/example-merge-plan";

export const EXAMPLE_REPORT = data as Report;

/** "1 June 2026": the date the recorded run read GitHub up to. */
export function exampleRecordedOn(report: Report = EXAMPLE_REPORT): string {
  return new Date(report.evidence_until ?? report.generated_at).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}
