"""The public example AI report stays in step with the pipeline.

web/src/lib/example-ai-report.json is generated by replaying a recorded run.
If a change to the pipeline, the checks on quotes and narration, or the report
shape would change it, this fails until the file is regenerated:

    uv run python scripts/build_example_report.py
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "build_example_report.py"


@pytest.fixture(scope="module")
def script():
    spec = importlib.util.spec_from_file_location("build_example_report", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_committed_example_matches_a_fresh_replay(script):
    committed = script.OUT.read_text(encoding="utf-8")
    assert committed == script.render(script.build()), (
        "the example AI report is stale: run "
        "`uv run python scripts/build_example_report.py` and commit the result"
    )


def test_example_is_a_clean_ai_report(script):
    report = json.loads(script.OUT.read_text(encoding="utf-8"))
    assert script.check_report(report) == []
    assert report["mode"] == "ai"
    # Recorded, not made now: the time fields must not depend on the clock.
    assert report["generated_at"] == report["evidence_until"]
    assert report["cost"]["seconds"] is None


def test_bad_examples_are_refused(script):
    report = json.loads(script.OUT.read_text(encoding="utf-8"))
    report["bottom_line"] = None
    report["evidence"] = [e | {"quote": None} for e in report["evidence"]]
    problems = script.check_report(report)
    assert any("bottom line" in p for p in problems)
    assert any("quoted threads" in p for p in problems)
