"""Stage D — the only stage that removes things.

Two mechanical checks, both of which delete rather than soften.

**Resolution.** Every finding carries the evidence ids that support it. This
resolves each one against the provider. A finding whose evidence does not
resolve is dropped: the alternative is prose that hedges around a claim nobody
can check, which is how unsupported statements survive into reports.

**Quotation.** A claim can cite a pull request that exists and still put words
in its mouth -- or put the author's own words in a maintainer's mouth. `eval/evidence_integrity.py` has measured that gap since Iteration
11 -- it is the difference between an id that resolves and evidence that says
what the claim says -- and the check here is the same function the metric uses,
so the number the eval reports and the guarantee the reader gets cannot drift
apart. A quote that is not in the record takes its claim with it, for the same
reason: keeping the outcome while deleting the fabricated quote is softening.

No model runs here. Resolution is a lookup and quotation is string matching.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from holt.agent.findings import Finding, Findings
from holt.evidence.provider import EvidenceProvider
from holt.types import EvidenceRecord

# A quote counts as present if a long-enough run of its words appears verbatim
# in the record. Models normalise whitespace and clip mid-sentence; penalising
# that would measure formatting rather than fidelity.
SHINGLE = 6

# `stages._render_thread` prefixes every reply with the speaker -- `[AUTHOR]`,
# `[octocat]` -- and a model quoting that reply routinely copies the prefix.
# Nobody said those words: they are ours. Stripping the tag before matching
# stops the guard blaming the model for our own formatting, which is the same
# lesson NO_REPLIES taught. What is left still has to be in the record, and a
# "quote" that is nothing *but* our scaffolding quotes nothing at all.
SPEAKER_TAG = re.compile(r"^\s*\[[^\]]{1,40}\]\s*")


def verify(findings: Findings, provider: EvidenceProvider) -> tuple[Findings, list[Finding]]:
    """Return (surviving findings, dropped findings)."""
    kept, dropped = Findings(), []
    for item in findings:
        if not item.evidence_ids:
            dropped.append(item)
            continue
        resolved = tuple(e for e in item.evidence_ids if provider.resolve(e) is not None)
        if not resolved:
            dropped.append(item)
            continue
        kept.add(item.field, item.value, resolved, item.note)
    return kept, dropped


# Punctuation is folded away with the whitespace, for the same reason. A model
# that quotes ``[`nixpkgs-review`]``(...) as ``[`nixpkgs-review`].`` -- closing a
# markdown link it truncated -- has quoted the thread; rejecting it would be
# measuring punctuation. What survives folding is the words, and those still
# have to be the record's words, in the record's order.
_NON_WORD = re.compile(r"[^\w]+", re.UNICODE)


def normalise(text: str) -> str:
    return " ".join(_NON_WORD.sub(" ", (text or "").lower()).split())


def spoken_part(quote: str) -> str:
    """The words attributed to a person, with our speaker tag removed."""
    return SPEAKER_TAG.sub("", quote or "", count=1).strip()


def quote_supported(quote: str, haystack: str) -> bool:
    q, h = normalise(quote), normalise(haystack)
    if not q:
        return False
    words = q.split()
    if len(words) <= SHINGLE:
        return q in h
    return any(
        " ".join(words[i : i + SHINGLE]) in h for i in range(len(words) - SHINGLE + 1)
    )


# Text a program wrote, even when it was posted from a person's account.
# PostHog staff run a "QA Swarm" that posts reviews as themselves, prefixed
# "Automated comment by ... not written by a human"; nixpkgs-review posts
# "Generated using ..."; review bots open with an HTML comment marker. Quoting
# any of these as a maintainer's reaction is quoting a machine.
_AUTOMATED = re.compile(
    r"not written by a human|automated comment|auto-generated|autogenerated"
    r"|generated (?:using|by) \[?`?[\w.-]+|approved automatically"
    r"|this (?:is an|comment was) automated|automated (?:review|message|check)",
    re.IGNORECASE,
)
# A line addressed to a merge bot -- `@robodoo r+`, `@NixOS/nixpkgs-merge-bot
# merge`, `@bors try` -- is an instruction to a machine, not something said to
# the contributor.
_BOT_COMMAND = re.compile(
    r"^@(?:[\w./-]*bot\b[\w./-]*|robodoo|bors|homu|mergify)\s"
    r"|^@[\w./-]+\s+r[+-](?:\s|$)",
    re.IGNORECASE,
)


# A request to an AI assistant (`@claude review these changes`, `@copilot ...`,
# `/gemini review`) is said to a machine too. So is what the assistant posts
# back, often from the maintainer's own account: a review template that
# counts findings by severity ("## Review summary 🔴 1 blocker · 🟠 1 major")
# or the assistant's status line. pytorch's evidence list quoted both as
# maintainer review.
_AI_REQUEST = re.compile(
    r"^@(?:claude|copilot|codex|coderabbitai|gemini-code-assist|cursor|sourcery-ai"
    r"|devin-ai-integration|greptileai|qodo-merge-pro)\b"
    r"|^/(?:gemini|coderabbit|review|improve|describe)\b",
    re.IGNORECASE,
)
_AI_REVIEW = re.compile(
    r"^#{1,4}\W*(?:ai |automated |code )?review summary\b"
    r"|\d+\s+(?:blockers?|critical)\b[^\n]{0,40}\d+\s+(?:majors?|minors?|nits?)\b"
    r"|\bclaude (?:finished|is working on)\b|\bcopilot (?:reviewed|wasn't able)\b",
    re.IGNORECASE | re.MULTILINE,
)


def automated_body(body: str) -> bool:
    """Whether a comment or review body was written by, or for, a program."""
    text = (body or "").strip()
    if not text:
        return False
    if text.startswith("<!--"):
        return True
    head = text[:400]
    return bool(_AUTOMATED.search(head) or _BOT_COMMAND.match(text)
                or _AI_REQUEST.match(text) or _AI_REVIEW.search(head))


def knows_association(records: Iterable[EvidenceRecord]) -> bool:
    """Whether this capture says who has write access.

    Captures before the v2 evidence (every committed benchmark fixture) do not;
    live reads always do.
    """
    return any(
        "author_association" in r.payload
        for r in records if r.evidence_id.endswith(":opened")
    )


def pr_authors(records: Iterable[EvidenceRecord]) -> dict[str, str]:
    """Who opened each pull request, keyed by its number."""
    return {
        number: record.payload.get("author") or ""
        for record in records
        if record.evidence_id.endswith(":opened")
        and (number := _pr_number(record.evidence_id)) is not None
    }


def spoken_words(records: Iterable[EvidenceRecord]) -> dict[str, str]:
    """What the project's team said on each pull request.

    On evidence that records who has write access (every live read), only
    people `people.maintainers` counts as the team are heard: a bystander's
    question ("have you used this fix in production?") presented as the
    project asking for changes, or an unrelated account's "Retracted.", is a
    quote from the wrong person. Older captures can't tell who is who, and
    keep the rule below: anyone but the author.

    Quotes come from reviews and comments, which live in their own records
    (`#12:review:0`, `#12:comment:1`) rather than in the `:opened` record a
    Stage C finding cites, so the haystack is the whole thread.

    The speaker matters as much as the words. Every thread-outcome quote is
    presented as the project's reaction -- a review, a request for changes, a
    reason for closing -- so the haystack leaves out the pull request's own
    title and description, the author's replies, bot accounts and automated
    bodies. Before this, the author's description of their own change passed as
    a maintainer's review (JhaSourav07/commitpulse #1956, #1927), and a staff
    member's automated QA post on their own pull request passed as outsider
    feedback (PostHog/posthog #60677).
    """
    from holt.agent.people import maintainers
    from holt.agent.signals import looks_like_bot

    records = list(records)
    authors = pr_authors(records)
    team = maintainers(records) if knows_association(records) else None
    said: dict[str, list[str]] = {}
    for record in records:
        number = _pr_number(record.evidence_id)
        if number is None or record.evidence_id.endswith(":opened"):
            continue
        payload = record.payload
        who = payload.get("author") or ""
        if who and who == authors.get(number):
            continue
        if looks_like_bot(who, bool(payload.get("author_is_bot"))):
            continue
        if team is not None and who not in team:
            continue
        body = payload.get("body") or ""
        if not body.strip() or automated_body(body):
            continue
        said.setdefault(number, []).append(body)
    return {k: " ".join(v) for k, v in said.items()}


def _pr_number(evidence_id: str) -> str | None:
    if "#" not in evidence_id:
        return None
    return evidence_id.split("#")[-1].split(":")[0]


def check_quotes(
    findings: Findings, records: Iterable[EvidenceRecord]
) -> tuple[list[Finding], list[Finding]]:
    """Split findings into (quoting the record, putting words in its mouth).

    Findings that quote nothing pass through untouched -- there is nothing to
    check and nothing to accuse them of.
    """
    said = spoken_words(records)
    supported, invented = [], []
    for item in findings:
        raw = item.value.get("quote", "") if isinstance(item.value, dict) else ""
        if not raw or not str(raw).strip():
            supported.append(item)
            continue
        quote = spoken_part(str(raw))
        if not quote:
            # Entirely our own scaffolding. There is no quotation here to check,
            # and printing `“[octocat]”` to a reader is not evidence of anything.
            invented.append(item)
            continue
        number = _pr_number(item.evidence_ids[0]) if item.evidence_ids else None
        if number is not None and quote_supported(quote, said.get(number, "")):
            supported.append(item)
        else:
            invented.append(item)
    return _without_unfounded_readings(supported, invented)


def _without_unfounded_readings(
    supported: list[Finding], invented: list[Finding]
) -> tuple[list[Finding], list[Finding]]:
    """Move a posture reading out when most of the threads it cites failed the quote check.

    Stage C's overall posture ("welcoming", "mixed") is its reading of the same
    threads it quoted. When most of those quotes were the author's own words or
    a program's, the reading was built on them: PostHog/posthog was called
    welcoming on the strength of a staff member's automated QA posts on their
    own pull requests. The reading goes the same way as its quotes.
    """
    failed = {_pr_number(e) for i in invented for e in i.evidence_ids[:1]}
    kept = []
    for item in supported:
        cited = {_pr_number(e) for e in item.evidence_ids}
        if item.field == "outsider_posture" and cited and len(cited & failed) * 2 > len(cited):
            invented.append(item)
        else:
            kept.append(item)
    return kept, invented
