#!/usr/bin/env bash
# Write deploy/staging/.env for the staging stack (next to compose.yml).
# Keeps an existing file unless --force: rotating HOLT_SECRET_KEY makes saved
# BYOK keys unreadable, and HOLT_DB_PASSWORD is baked into the db volume.
#
# STAGING_HOST is the only place the site's address is written; compose.yml
# and preview.sh make every URL from it.
set -euo pipefail
cd "$(dirname "$0")"
if [[ -f .env && "${1:-}" != "--force" ]]; then
    echo ".env exists; leaving it (pass --force to regenerate)"; exit 0
fi
rand() { python3 -c "import os,base64;print(base64.b64encode(os.urandom(32)).decode())"; }
hex() { python3 -c "import secrets;print(secrets.token_hex(24))"; }
token="$(gh auth token)"
umask 077
cat > .env <<ENV
# Holt staging. Generated by make-env.sh on $(date -u +%FT%TZ). Never commit.
HOLT_ENV=staging
HOLT_STAGE_PORT=${HOLT_STAGE_PORT:-9110}
STAGING_HOST=${STAGING_HOST:-staging.githolt.com}
HOLT_INTERNAL_KEY=$(hex)
HOLT_SECRET_KEY=$(rand)
AUTH_SECRET=$(rand)
HOLT_DB_PASSWORD=$(hex)
GITHUB_TOKENS=$token
# No model key yet: AI reports answer needs_key.
OPENROUTER_API_KEY=
# The policy pages' contact details and the sign-in keys are not here:
# preview.sh reads CONTACT_EMAIL / CONTACT_CITY and the optional
# STAGING_*_OAUTH_* from ~/.config/holt/secrets.env on every run.
HOLT_JOB_CONCURRENCY=1
ENV
echo "wrote $(pwd)/.env"
