"""Grow server/holt_server/seeds/repos.txt from free public lists, without GitHub search.

Sources (downloaded as plain files, no GitHub API):
  - GSoC 2026 organisations: summerofcode.withgoogle.com's public org API. An org
    whose source link is a repository is taken as is; an org link is mapped to its
    main contribution repos by hand (GSOC_ORG_REPOS below); CNCF is mapped to its
    graduated, incubating and sandbox projects from cncf/landscape's landscape.yml.
    Orgs not on GitHub
    (or only mirrored there) are skipped.
  - awesome-for-beginners (MunGell/awesome-for-beginners, README.md).
  - up-for-grabs (up-for-grabs/up-for-grabs.net, _data/projects/*.yml). Projects
    whose label stats were last updated before UFG_ACTIVE_SINCE are dropped.
  - goodfirstissue.dev (deepsourcelabs/good-first-issue, data/repositories.toml).
  - Hacktoberfest: `--hacktoberfest FILE`, one owner/repo per line (an export of
    repos Holt already knows that carry the `hacktoberfest` topic).

Everything above the GENERATED marker in repos.txt is kept verbatim; everything
below it is rebuilt. Catalogues (awesome-*, *-list, book lists, registries) and
contribution farms are dropped by name.

`--check` runs one batched GraphQL pass (100 repos per query, about 1 point per
query) and drops repos that are gone, archived, forks, or not pushed since
CHECK_ACTIVE_SINCE or under MIN_STARS stars, and writes renamed repos under their current name. It reads
GITHUB_TOKEN.

    GITHUB_TOKEN=$(gh auth token) uv run python scripts/build_seed_list.py --check \\
        [--hacktoberfest repos.txt] [--dry-run]
"""

from __future__ import annotations

import argparse
import io
import json
import os
import re
import sys
import tarfile
import tomllib
import urllib.request
from collections import Counter
from pathlib import Path

SEEDS = Path(__file__).resolve().parents[1] / "server" / "holt_server" / "seeds" / "repos.txt"
MARKER = "# ---- generated by scripts/build_seed_list.py; edit above this line ----"

GSOC_URL = "https://summerofcode.withgoogle.com/api/program/2026/organizations/"
AFB_URL = "https://raw.githubusercontent.com/MunGell/awesome-for-beginners/main/README.md"
CNCF_URL = "https://raw.githubusercontent.com/cncf/landscape/master/landscape.yml"
UFG_URL = "https://codeload.github.com/up-for-grabs/up-for-grabs.net/tar.gz/refs/heads/gh-pages"
GFI_URL = "https://raw.githubusercontent.com/deepsourcelabs/good-first-issue/master/data/repositories.toml"

UFG_ACTIVE_SINCE = "2025-01-01"
CHECK_ACTIVE_SINCE = "2025-01-01"
MIN_STARS = 20  # below this, a listed repo is almost always a personal project

# GSoC 2026 orgs whose source link is an org (or an umbrella/idea page), mapped to
# the repos where contributors actually open pull requests.
GSOC_ORG_REPOS: dict[str, list[str]] = {
    "aboutcode-org": ["aboutcode-org/scancode-toolkit", "aboutcode-org/vulnerablecode",
                      "aboutcode-org/scancode.io"],
    "accordproject": ["accordproject/concerto", "accordproject/template-playground"],
    "AOSSIE-Org": ["AOSSIE-Org/PictoPy"],
    "apache": ["apache/airflow", "apache/superset", "apache/beam", "apache/datafusion",
               "apache/iceberg"],
    "ArduPilot": ["ArduPilot/ardupilot", "ArduPilot/MissionPlanner"],
    "c2siorg": ["c2siorg/Webiu"],
    "Catrobat": ["Catrobat/Catroid", "Catrobat/Paintroid"],
    "cBioPortal": ["cBioPortal/cbioportal", "cBioPortal/cbioportal-frontend"],
    "CCExtractor": ["CCExtractor/ccextractor"],
    "ceph": ["ceph/ceph"],
    "checkstyle": ["checkstyle/checkstyle"],
    "circuitverse": ["CircuitVerse/CircuitVerse", "CircuitVerse/cv-frontend-vue"],
    "dart-lang": ["dart-lang/site-www", "dart-lang/pub-dev"],
    "dbpedia": ["dbpedia/extraction-framework"],
    "dlang": ["dlang/dmd", "dlang/phobos"],
    "dora-rs": ["dora-rs/dora"],
    "Ensembl": ["Ensembl/ensembl-vep"],
    "fortran-lang": ["fortran-lang/stdlib", "fortran-lang/fpm", "lfortran/lfortran"],
    "fossasia": ["fossasia/eventyay", "fossasia/badgemagic-app", "fossasia/pslab-app"],
    "GeomScale": ["GeomScale/volesti"],
    "haskell": ["haskell/cabal", "haskell/haskell-language-server"],
    "HSF": ["root-project/root"],
    "internetarchive": ["internetarchive/openlibrary"],
    "jderobot": ["JdeRobot/RoboticsAcademy"],
    "jenkinsci": ["jenkinsci/jenkins"],
    "jitsi": ["jitsi/jitsi-meet"],
    "json-schema-org": ["json-schema-org/website", "json-schema-org/json-schema-spec"],
    "kubeflow": ["kubeflow/pipelines", "kubeflow/trainer"],
    "kubevirt": ["kubevirt/kubevirt"],
    "learning-unlimited": ["learning-unlimited/ESP-Website"],
    "malariagen": ["malariagen/malariagen-data-python"],
    "meshery": ["meshery/meshery"],
    "metabrainz": ["metabrainz/musicbrainz-server", "metabrainz/listenbrainz-server",
                   "metabrainz/picard"],
    "metacall": ["metacall/core"],
    "mofa-org": ["mofa-org/mofa"],
    "neuroinformatics-unit": ["neuroinformatics-unit/movement"],
    "neutralinojs": ["neutralinojs/neutralinojs"],
    "ohcnetwork": ["ohcnetwork/care_fe", "ohcnetwork/care"],
    "omegaup": ["omegaup/omegaup"],
    "onebusaway": ["OneBusAway/onebusaway-android"],
    "openfoodfacts": ["openfoodfacts/openfoodfacts-server", "openfoodfacts/smooth-app",
                      "openfoodfacts/robotoff"],
    "openmf": ["openMF/web-app", "openMF/mifos-mobile", "openMF/android-client"],
    "openmrs": ["openmrs/openmrs-core", "openmrs/openmrs-esm-patient-chart"],
    "openrobotics": ["gazebosim/gz-sim", "ros2/ros2_documentation"],
    "openstreetmap": ["openstreetmap/openstreetmap-website", "openstreetmap/iD"],
    "openSUSE": ["openSUSE/open-build-service"],
    "openvinotoolkit": ["openvinotoolkit/openvino"],
    "openwisp": ["openwisp/openwisp-controller"],
    "OSGeo": ["OSGeo/gdal", "OSGeo/grass", "qgis/QGIS"],
    "owasp": ["OWASP/Nettacker", "zaproxy/zaproxy", "juice-shop/juice-shop"],
    "p4lang": ["p4lang/p4c"],
    "precice": ["precice/precice"],
    "processing": ["processing/p5.js", "processing/processing4"],
    "rizinorg": ["rizinorg/rizin", "rizinorg/cutter"],
    "ruby": ["ruby/ruby"],
    "scummvm": ["scummvm/scummvm"],
    "search": ["mandiant/capa", "mandiant/flare-floss"],  # FLARE links a topic search
    "stjude-rust-labs": ["stjude-rust-labs/sprocket"],
    "Submitty": ["Submitty/Submitty"],
    "sugarlabs": ["sugarlabs/musicblocks", "sugarlabs/sugar"],
    "tardis-sn": ["tardis-sn/tardis"],
    "typelevel": ["typelevel/cats", "typelevel/cats-effect"],
    "unikraft": ["unikraft/unikraft"],
    "webpack": ["webpack/webpack", "webpack/webpack.js.org"],
    "kiwix": ["kiwix/kiwix-android", "kiwix/kiwix-js"],
    # Umbrellas whose link is an idea page, not a repository.
    "numfocus/gsoc": ["numpy/numpy", "pandas-dev/pandas", "matplotlib/matplotlib",
                      "scipy/scipy", "jupyterlab/jupyterlab"],
}
# Non-GitHub source links whose projects do take pull requests on GitHub.
GSOC_OFF_GITHUB: dict[str, list[str]] = {
    "python-gsoc.org": ["python/cpython"],
    "openastronomy.org": ["astropy/astropy", "sunpy/sunpy"],
}

# Catalogues and farms, by name. The engine labels catalogues anyway; warming them
# wastes points.
SKIP_NAME = re.compile(
    r"(^|[-_.])(awesome|list|lists|books?|resources|roadmaps?|cheatsheets?|"
    r"interview|curated|collection|algorithms?|snippets?|practice)([-_.]|$)|^awesome|awesome$|"
    r"first[-_]?contributions?|hacktoberfest|add[-_]?your[-_]?name|contributors?[-_]list|"
    r"^is-a-dev$|^register$|^public-apis$|^free-programming-books",
    re.I,
)
SKIP_REPOS = {
    "freecodecamp/freecodecamp",  # a curriculum site, kept only if already seeded
    "is-a-dev/register", "open-domains/register", "js-org/js.org",
    "ossu/computer-science", "trekhleb/javascript-algorithms", "thealgorithms/python",
    "thealgorithms/java", "thealgorithms/javascript", "thealgorithms/c-plus-plus",
    "thealgorithms/c", "thealgorithms/go", "thealgorithms/rust", "thealgorithms/c-sharp",
    "kamranahmedse/developer-roadmap", "ebookfoundation/free-programming-books",
    "theodinproject/curriculum", "magicianred/learn-by-doing", "eskayml/turtle-projects",
    "gimseng/99-ml-learning-projects", "meilynbear/beginnersmakelistpractice",
}

GH_REPO = re.compile(r"github\.com/([A-Za-z0-9-]+)/([A-Za-z0-9_.-]+)")


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "holt-seed-builder"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def repo_from(url: str) -> str | None:
    m = GH_REPO.search(url)
    if not m:
        return None
    owner, name = m.group(1), m.group(2).removesuffix(".git")
    if owner.lower() in {"orgs", "search", "topics", "sponsors", "apps", "marketplace"}:
        return None
    return f"{owner}/{name}"


def cncf() -> list[str]:
    import yaml  # installed with the server's dependencies

    out = []
    for cat in yaml.safe_load(get(CNCF_URL))["landscape"]:
        for sub in cat.get("subcategories") or []:
            for item in sub.get("items") or []:
                if item.get("project") in {"graduated", "incubating", "sandbox"}:
                    if r := repo_from(item.get("repo_url") or ""):
                        out.append(r)
    return out


def gsoc() -> list[str]:
    out: list[str] = []
    for org in json.loads(get(GSOC_URL)):
        url = org["source_code"].rstrip("/")
        if "github.com" not in url:
            host = url.split("/")[2] if "//" in url else url
            out += GSOC_OFF_GITHUB.get(host, [])
            continue
        path = url.split("github.com/", 1)[1].split("#")[0].split("?")[0]
        parts = [p for p in path.split("/") if p]
        key = "/".join(parts[:2]).lower() if len(parts) >= 2 else parts[0]
        umbrella = {k.lower(): v for k, v in GSOC_ORG_REPOS.items()}
        if key == "cncf":
            out += cncf()
        elif key in umbrella:
            out += umbrella[key]
        elif len(parts) == 1 or parts[0] == "search":
            out += umbrella.get(parts[0].lower(), [])
        elif parts[1] not in {".github", "ProjectIdeas", "GSoC", "gsoc"}:
            out.append(f"{parts[0]}/{parts[1]}")
    return out


def afb() -> list[str]:
    text = get(AFB_URL).decode("utf-8")
    return [r for u in re.findall(r"\]\((https://github\.com/[^)\s]+)\)", text)
            if (r := repo_from(u))]


def ufg() -> list[str]:
    out = []
    with tarfile.open(fileobj=io.BytesIO(get(UFG_URL)), mode="r:gz") as tar:
        for member in tar:
            if "/_data/projects/" not in member.name or not member.name.endswith(".yml"):
                continue
            text = tar.extractfile(member).read().decode("utf-8", "replace")
            site = re.search(r"^site:\s*(\S+)", text, re.M)
            updated = re.search(r"last-updated:\s*'?\"?(\d{4}-\d{2}-\d{2})", text)
            if not site or not updated or updated.group(1) < UFG_ACTIVE_SINCE:
                continue
            if r := repo_from(site.group(1)):
                out.append(r)
    return out


def gfi() -> list[str]:
    data = tomllib.loads(get(GFI_URL).decode("utf-8"))
    return [r for u in data["repositories"] if (r := repo_from(u))]


def skipped(repo: str) -> bool:
    return repo.lower() in SKIP_REPOS or bool(SKIP_NAME.search(repo.split("/")[1]))


def check(repos: list[str], token: str) -> tuple[dict[str, str | None], int]:
    """repo -> current nameWithOwner, or None when gone/archived/fork/dead.
    Returns the map and the GraphQL points it cost."""
    result: dict[str, str | None] = {}
    cost = 0
    for i in range(0, len(repos), 100):
        chunk = repos[i:i + 100]
        fields = "nameWithOwner isArchived isFork pushedAt stargazerCount"
        body = " ".join(
            f'r{j}: repository(owner: {json.dumps(r.split("/")[0])}, '
            f'name: {json.dumps(r.split("/")[1])}) {{ {fields} }}'
            for j, r in enumerate(chunk))
        query = f"query {{ rateLimit {{ cost }} {body} }}"
        req = urllib.request.Request(
            "https://api.github.com/graphql", data=json.dumps({"query": query}).encode(),
            headers={"Authorization": f"bearer {token}", "User-Agent": "holt-seed-builder"})
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read())["data"]
        cost += data["rateLimit"]["cost"]
        for j, r in enumerate(chunk):
            node = data.get(f"r{j}")
            ok = (node and not node["isArchived"] and not node["isFork"]
                  and (node["pushedAt"] or "") >= CHECK_ACTIVE_SINCE
                  and node["stargazerCount"] >= MIN_STARS)
            result[r] = node["nameWithOwner"] if ok else None
    return result, cost


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--hacktoberfest", help="file of owner/repo with the hacktoberfest topic")
    ap.add_argument("--check", action="store_true", help="one batched GraphQL liveness pass")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    text = SEEDS.read_text(encoding="utf-8")
    head = text.split(MARKER, 1)[0].rstrip("\n")
    seen = {line.split("#", 1)[0].strip().lower() for line in head.splitlines()} - {""}
    kept = len(seen)

    sources: list[tuple[str, str, list[str]]] = []
    if args.hacktoberfest:
        lines = Path(args.hacktoberfest).read_text(encoding="utf-8").splitlines()
        sources.append(("hacktoberfest", "repos Holt has seen with the hacktoberfest topic",
                        [r for line in lines if (r := repo_from("github.com/" + line.strip()))]))
    sources += [
        ("gsoc-2026", f"GSoC 2026 organisations ({GSOC_URL}), orgs mapped by hand", gsoc()),
        ("goodfirstissue.dev", GFI_URL, gfi()),
        ("awesome-for-beginners", AFB_URL, afb()),
        ("up-for-grabs", f"{UFG_URL} (label stats updated since {UFG_ACTIVE_SINCE})", ufg()),
    ]

    dropped: Counter[str] = Counter()
    blocks: list[tuple[str, str, list[str]]] = []
    for name, where, found in sources:
        new = []
        for repo in found:
            if repo.lower() in seen:
                dropped["duplicate"] += 1
            elif skipped(repo):
                dropped["catalogue or farm"] += 1
                seen.add(repo.lower())
            else:
                seen.add(repo.lower())
                new.append(repo)
        blocks.append((name, where, new))

    if args.check:
        token = os.environ.get("GITHUB_TOKEN")
        if not token:
            sys.exit("--check needs GITHUB_TOKEN")
        status, cost = check([r for _, _, b in blocks for r in b], token)
        print(f"GraphQL check cost {cost} points", file=sys.stderr)
        seen = {line.split("#", 1)[0].strip().lower() for line in head.splitlines()} - {""}
        checked = []
        for name, where, new in blocks:
            live = []
            for repo in new:
                current = status.get(repo)
                if current is None:
                    dropped[f"gone, archived, fork, under {MIN_STARS} stars or no push since {CHECK_ACTIVE_SINCE}"] += 1
                elif current.lower() in seen:
                    dropped["duplicate after rename"] += 1
                else:
                    seen.add(current.lower())
                    live.append(current)
            checked.append((name, where, live))
        blocks = checked

    out = [head, "", MARKER]
    for name, where, new in blocks:
        out += ["", f"# source: {name} ({len(new)}) {where}"] + sorted(new, key=str.lower)
    total = kept + sum(len(b) for _, _, b in blocks)
    for name, _, new in blocks:
        print(f"{name}: {len(new)} new", file=sys.stderr)
    for why, n in dropped.most_common():
        print(f"dropped ({why}): {n}", file=sys.stderr)
    print(f"kept {kept} existing; total {total}", file=sys.stderr)
    if not args.dry_run:
        SEEDS.write_text("\n".join(out) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
