#!/usr/bin/env bash
# Regenerate web/src/lib/api-schema.ts from the server's pydantic models.
#
#   server/scripts/api_types.sh          # write it
#   server/scripts/api_types.sh --check  # fail if the checked-in file is stale (CI)
#
# Needs `uv sync` at the repo root and `npm ci` in web/.
set -euo pipefail
root="$(cd "$(dirname "$0")/../.." && pwd)"
out="$root/web/src/lib/api-schema.ts"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

(cd "$root" && uv run --quiet python server/scripts/export_openapi.py) > "$tmp/openapi.json"
"$root/web/node_modules/.bin/openapi-typescript" "$tmp/openapi.json" -o "$tmp/api-schema.ts" --root-types --root-types-no-schema-prefix >/dev/null
{
  echo "// GENERATED by server/scripts/api_types.sh from the server's pydantic models"
  echo "// (server/holt_server/schema.py). Do not edit; run the script instead."
  cat "$tmp/api-schema.ts"
} > "$tmp/final.ts"

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -u "$out" "$tmp/final.ts"; then
    echo "web/src/lib/api-schema.ts is out of date: run server/scripts/api_types.sh" >&2
    exit 1
  fi
  echo "api-schema.ts is up to date"
else
  cp "$tmp/final.ts" "$out"
  echo "wrote $out"
fi
